<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Toolshed Inc.</title>
    <link rel="stylesheet" type="text/css" href="http://<?= $_SERVER['HTTP_HOST'] ?>/static/style/site.css">
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"
            integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
            crossorigin="anonymous"></script>
    <?php if ($scripts) {
        foreach ($scripts as $script) { ?>
            <script type="text/javascript" src="http://<?= $_SERVER['HTTP_HOST'] ?>/src/js/<?= $script ?>.js"></script>
        <?php }
    } ?>
</head>
<body>
