<div class="navigation_bar">
    <ul>
        <li><a <?= explode('?', $_SERVER['REQUEST_URI'])[0] == '/' ? 'class="active"' : "" ?>
               href="http://<?= $_SERVER['HTTP_HOST'] ?>">Welcome</a></li>
        <li><a <?= explode('?', $_SERVER['REQUEST_URI'])[0] == '/search' ? 'class="active"' : "" ?>
               href="http://<?= $_SERVER['HTTP_HOST'] ?>/search">Search</a></li>
        <li class="logout"><a href="http://<?= $_SERVER['HTTP_HOST'] ?>/logout">Logout</a></li>
    </ul>
</div>
