<?php include HEADER_COMPONENT."default.phtml" ?>
<?php include IMAGE_COMPONENT."logo.phtml" ?>
<div class="container">
    <?php include MENU_COMPONENT."navigationBar.phtml" ?>
    <div class="search_box">
        <h1 id="title">Search</h1>
        <input type="search" placeholder="Enter keyword" value="<?= $_GET['needle'] ?>">
        <div class="clear"></div>
        <br>
        <table id="search_results">
            <tr id="header">
                <th class="sku">SKU</th>
                <th class="name">Name</th>
                <th class="category">Category</th>
                <th class="cost, currency">Cost</th>
                <th class="stock, number">Stock Qty</th>
            </tr>
            <?php if ($products) {
                foreach ($products as $product) { ?>
                <tr class="data_row">
                    <td class="sku"><?= $product->getSKU() ?></td>
                    <td class="name"><?= $product->getName() ?></td>
                    <td class="category"><?= $product->getCategory() ?></td>
                    <td class="cost, currency"><?= $product->getCostString() ?></td>
                    <td class="stock, number"><?= $product->getStock() ?></td>
                </tr>
                <?php }
            } ?>
        </table>
    </div>
</div>
<?php include FOOTER_COMPONENT."default.phtml" ?>

