<?php include HEADER_COMPONENT."default.phtml" ?>
<?php include IMAGE_COMPONENT."logo.phtml"; ?>
<div class="container">
    <h1 id="title">Registration form</h1>
    <br>
    <p class="text_centred"><b><?= $formError ? $formError : '' ?></b></p>
    <br>
    <div  class="float_center">
        <div class="float_center_child">
            <form id="user_registration_form" method="POST">
                <table>
                    <tr>
                        <td><label>Name</label></td>
                        <td>
                            <input name="name"
                                   placeholder="Name" value="<?= $name ?>" required>
                            <span><p class="error"></p></span>
                        </td>
                        <td id="name_alert"></td>
                    </tr>
                    <tr>
                        <td><label>Username</label></td>
                        <td>
                            <input name="username"
                                   placeholder="Username" value="<?= $username ?>" required>
                            <span><p class="error"></p></span>
                        </td>
                    </tr>
                    <tr>
                        <td><label>Password</label></td>
                        <td>
                            <input name="password" type="password"
                                   placeholder="Password" value="<?= $password ?>" required>
                            <span><p class="error"></p></span>
                        </td>
                    </tr>
                    <tr>
                        <td><label>Repeat</label></td>
                        <td>
                            <input name="passwordRepeat" type="password"
                                   placeholder="Password" value="<?= $passwordRepeat ?>" required>
                            <span><p class="error"></p></span>
                        </td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>
                            <button name="register">Register</button>
                        </td>
                    </tr>
                </table>
            </form>
        </div>
    </div>
</div>
<?php include FOOTER_COMPONENT."default.phtml" ?>
