<?php include HEADER_COMPONENT."default.phtml"; ?>
<h1>Login</h1>
<form method="POST">
    <table>
        <tr>
            <td><label>Username</label></td>
            <td>
                <input placeholder="Enter Username" name="username" value="<?= $username ? $username : '' ?>" required>
            </td>
        </tr>
        <tr>
            <td><label>Password</label></td>
            <td>
                <input type="password" placeholder="Enter Password" name="password" required>
            </td>
        </tr>
        <tr>
            <td></td>
            <td><button class="action" name="login">Login</button></td>
        </tr>
    </table>
</form>
<?= $username ? '<p>Invalid username and/or password.</p>' : '' ?>
<p>Don't have an account? <?php include BUTTON_COMPONENT."userRegister.phtml"; ?></p>
<?php include FOOTER_COMPONENT."default.phtml"; ?>
