<!-- Base code provided by Andrew Gilman <a.gilman@massey.ac.nz> -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Account Management Ltd</title>
    <link rel="stylesheet" type="text/css" href="/static/styles/site.css">
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"
            integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
            crossorigin="anonymous"></script>
    <?php if ($scripts) {
        foreach ($scripts as $script) { ?>
            <script type="text/javascript" src="/src/js/<?= $script ?>.js"></script>
        <?php }
    } ?>
</head>
<body>
    <div class="container">
