<!-- Base code provided by Andrew Gilman <a.gilman@massey.ac.nz> -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Account Management Ltd</title>
    <link rel="stylesheet" type="text/css" href="/static/styles/site.css">
    <?php if ($scripts) {
        foreach ($scripts as $script) {
            include "../scripts/$script.js";
        }
    } ?>
</head>
<body>
    <div class="container">
