<?php include "header.phtml" ?>
<h1>Login</h1>
<form method="POST">
    <table>
        <tr>
            <td class="login_username_title"><label>Username</label></td>
            <td class="login_username_input">
                <input placeholder="Enter Username" name="username" value="<?= $username ? $username : '' ?>" required>
            </td>
        </tr>
        <tr>
            <td class="login_password_title"><label>Password</label></td>
            <td class="login_password_input">
                <input type="password" placeholder="Enter Password" name="password" required>
            </td>
        </tr>
        <tr>
            <td></td>
            <td class="login_button"><button name="login">Login</button></td>
        </tr>
    </table>
</form>
<?= $username ? '<p>Invalid username and/or password.</p>' : '' ?>
<p>Don't have an account? <?php include "buttonRegister.phtml" ?></p>
<?php include "footer.phtml" ?>
